{
	"id" : "skuidmobilecore",
	"components" : [
		{ "id" : "skuidmobile", "pathsToChildComponents" : ["mobilepanels>mobilepanel>components","mobilenavs>mobilenav>components"] },
		{ "id" : "mobiledeck", "pathsToChildComponents" : ["components"] },
		{ "id" : "mobilegrid", "pathsToChildComponents" : ["divisions"]  },
		{ "id" : "mobilebutton" },
		{ "id" : "template" },
		{ "id" : "mobiletitle" },
		{ "id" : "mobileinfo" },
		{ "id" : "mobilefield" },
		{ "id" : "mobilewrapper", "pathsToChildComponents" : ["components"] },
		{ "id" : "mobileimage" },
		{ "id" : "custom" },
		{ "id" : "division", "pathsToChildComponents" : ["components"] },
		{ "id" : "file" }
	],
	"folders" : [],
	"js" : [
		{ "path" : "runtime.js" }
	]
}